language: go

go:
    - stable
    - 1.12.x
    - 1.11.x

sudo: required
dist: xenial

go_import_path: github.com/dutchsec/beagle

os:
    - linux

env:
    - GIMME_OS=linux GIMME_ARCH=amd64 GO111MODULE=on

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y software-properties-common python-software-properties
    - go get github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/tcnksm/ghr
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin

install:
    - go get -v github.com/dutchsec/beagle

script:
    - $GOPATH/bin/golangci-lint run
    - if [[ -z "$(go version | grep '1\.9')" ]]; then go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...; else go test -v ./...; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
